; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Examine the effect of the configuration with:
; pio|platformio run -v -e <environment>

[commoncpp]
build_flags = -std=c++23
build_unflags = -std=c++11 -std=c++14 -std=c++17 -std=c++20

[commonesp]
extends = commoncpp
platform = espressif32
framework = espidf
monitor_speed = 115200

[release]
build_flags = -D RELEASE -Os -fexceptions

[debug]
extends = release
build_type = debug
build_flags = -D DEBUG -Og -g3
build_unflags = -D RELEASE -Os

[embedded]
extends = commonesp
test_framework = unity

[env:native]
extends = commoncpp
platform = native
test_framework = unity
test_ignore = envEmbedded

[env:esp32-s3-devkitc-1]
extends = embedded, release
board = esp32-s3-devkitc-1
board_build.flash_size = 8MB
